development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: gingolingo_development
  pool: 5
  username: gingolingo
  password: gingolingo

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: gingolingo_test
  pool: 5
  username: gingolingo
  password: gingolingo